[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Node"
name = "sn_node"
version = "0.83.0"
edition = "2021"
license = "GPL-3.0"
homepage = "https://maidsafe.net"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"

[[bin]]
name = "safenode"
path = "src/bin/safenode/main.rs"

[[bin]]
name = "faucet"
path = "src/bin/faucet.rs"

[features]
default=[]
local-discovery=["sn_networking/local-discovery"]

[dependencies]
async-trait = "0.1"
bincode = "1.3.1"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
clap = { version = "4.2.1", features = ["derive"]}
crdts = { version = "7.3", default-features = false, features = ["merkle"] }
chrono = "~0.4.19"
custom_debug = "~0.5.0"
dirs-next = "~2.0.0"
eyre = "0.6.8"
file-rotate = "0.7.3"
futures = "~0.3.13"
hex = "~0.4.3"
itertools = "~0.10.1"
lazy_static = "~1.4.0"
libp2p = { version="0.51", features = ["tokio", "dns", "kad", "macros", "autonat"] }
prost = { version = "0.9" }
rand = { version = "~0.8.5", features = ["small_rng"] }
rmp-serde = "1.1.1"
rayon = "~1.5.1"
self_encryption = "~0.28.0"
serde = { version = "1.0.133", features = [ "derive", "rc" ]}
sn_build_info= { path="../sn_build_info", version="0.1.0" }
sn_peers_acquisition= { path="../sn_peers_acquisition", version="0.1.0" }
sn_dbc = { version = "18.0.0", features = ["serdes"] }
sn_client = { path = "../sn_client", version = "0.85.0" }
sn_logging = { path = "../sn_logging", version = "0.1.0" }
sn_networking = { path = "../sn_networking", version = "0.1.0" }
sn_protocol = { path = "../sn_protocol", version = "0.1.0" }
sn_registers = { path = "../sn_registers", version = "0.1.0" }
sn_transfers = { path = "../sn_transfers", version = "0.1.0" }
thiserror = "1.0.23"
tiny-keccak = "~2.0.2"
tokio = { version = "1.17.0", features = ["fs", "io-util", "macros", "parking_lot", "rt", "sync", "time"] }
tokio-stream = { version = "~0.1.12" }
tonic = { version = "0.6.2" }
tracing = { version = "~0.1.26" }
tracing-appender = "~0.2.0"
tracing-core = "0.1.30"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
walkdir = "2.3.1"
xor_name = "5.0.0"
tracing-log = { version = "0.1.3", features = ["env_logger"] }

[dev-dependencies]
assert_fs = "1.0.0"

[build-dependencies]
tonic-build = { version = "0.6.2" }
