[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Safe Network CLI"
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_cli"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.77.0"

[[bin]]
path="src/main.rs"
name="safe"

[dependencies]
bincode = "1.3.1"
bls = { package = "blsttc", version = "8.0.1" }
bytes = { version = "1.0.1", features = ["serde"] }
chrono = "~0.4.19"
clap = { version = "4.2.1", features = ["derive"]}
color-eyre = "~0.6"
dirs-next = "~2.0.0"
hex = "~0.4.3"
libp2p = { version="0.51", features = ["identify", "kad"] }
sn_build_info= { path="../sn_build_info", version="0.1.0" }
sn_client = { path = "../sn_client", version = "0.85.0" }
sn_dbc = { version = "18.0.0", features = ["serdes"] }
sn_transfers = { path = "../sn_transfers", version = "0.1.0" }
sn_logging = { path = "../sn_logging", version = "0.1.0" }
sn_peers_acquisition= { path="../sn_peers_acquisition", version="0.1.0" }
sn_protocol = { path = "../sn_protocol", version = "0.1.0" }
tokio = { version = "1.17.0", features = ["fs", "io-util", "macros", "parking_lot", "rt", "sync", "time"] }
tracing = { version = "~0.1.26" }
tracing-core = "0.1.30"
walkdir = "2.3.1"
xor_name = "5.0.0"
